## PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb
spec:
  storageClassName: managed-nfs-storage #---指定StorageClass k  get  storageclasses.storage.k8s.io
  resources:
    requests:
      storage: 10Gi         #设置 pvc 存储资源大小
  accessModes:
  - ReadWriteOnce