apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-min-pv-local
  namespace: default
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-min-storageclass-nfs
  persistentVolumeReclaimPolicy: Retain
  #存储采用nfs
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /data/nfs/k8stest/7d/mysql
    server: 10.8.15.31
