apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage  # pv 使用的sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"   #---设置为默认的storageclass
provisioner: 10.8.15.31/nfs    #---动态卷分配者名称，必须和上面创建的"provisioner-deploy"变量 PROVISIONER_NAME 中设置的Name一致
parameters:
  archiveOnDelete: "false" #---设置为"false"时删除PVC不会保留数据,"true"则保留数据
